# Generated by Django 4.1.7 on 2023-05-01 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileProperties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("date_added", models.DateField(default=datetime.date.today)),
                ("original_url", models.CharField(max_length=255)),
                ("summary_url", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
