# Generated by Django 4.1.7 on 2023-05-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appsite", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileproperties",
            name="industry_tag",
            field=models.CharField(
                choices=[
                    ("it", "IT"),
                    ("food", "Food"),
                    ("medicine", "Medicine"),
                    ("general", "General"),
                ],
                default="general",
                max_length=255,
            ),
        ),
    ]
